name: Build

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: Build on ${{ matrix.cross }}
    strategy:
      fail-fast: false
      matrix:
        cross:
          - windows-latest
          - ubuntu-latest
          - macos-11
    runs-on: ${{ matrix.cross }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build project
        run: ./gradlew build --scan --info
